group 'appmire.be.flutterjailbreakdetection'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '2.0.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdk 36
    namespace project.group

    // compileOptions {
    //     sourceCompatibility JavaVersion.VERSION_17
    //     targetCompatibility JavaVersion.VERSION_17
    // }

    // sourceSets {
    //     main.java.srcDirs += 'src/main/kotlin'
    // }

    compileOptions {
        // coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }
    
    defaultConfig {
        minSdk 24
    }
    
    // namespace "appmire.be.flutterjailbreakdetection"
}

dependencies {
    implementation 'com.scottyab:rootbeer-lib:0.1.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    // coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.4'
}
